# Site settings
title: Vassilis Xanthopoulos
description: My portfolio website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi, I'm Vassilis
user_description: I'm Vassilis Xanthopoulos and I'm currently studying Electrical and Computer Engineer at ECE NTUA. My academic interests lie in the fields of Algorithms, Complexity and Mathematics. This is my personal website where I showcase my projects and more!
user_title: and I like mathematics and programming
email: xanthopoulos.vassilis@gmail.com
github_username: vilaras

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules']
