# Site settings
title: Stelios Giannelos
description: This is my portfolio website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Stelios Giannelos
user_description: Welcome to my website! Click below to view my CV, project portfolio and more 
user_title: Informatics & Computers Engineer
email: stylianos.giannelos@gmail.com
github_username: steliosgnl

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules']
